#!/usr/bin/env python3
import json
from pathlib import Path

with open(Path(__file__).resolve().parent/'tests.json') as ifh:
    tests = [ t for t in json.load(ifh) if not isinstance(t, str) ]

with open(Path(__file__).resolve().parent/'test_fp2conv_tests.inc.c','w') as ofh:
    print('// ***** DO NOT EDIT *****\n'
        f'// This file is generated by {Path(__file__).name}\n'
        f'#define NUM_TESTS ({len(tests)})\n'
        '// test string format:\n'
        '// [0]: "P"=strtofp2 only, "S"=fp2tostr only, "R"=both\n'
        '// [1-2]: the FP2 value\n'
        '// [3]: a space character\n'
        '// [4-]: the string\n'
        'char *TEST[NUM_TESTS] = {', file=ofh)
    for t,f,s in tests:
        if t not in ('P','S','R'): raise ValueError(f"invalid test type: {t!r}")
        if len(f)!=4 or not 0<=int(f,16)<=0xFFFF: raise ValueError(f"invalid fp2 value: {f!r}")
        if not isinstance(s,str) or '"' in s: raise ValueError(f"invalid string: {s!r}")
        print(f'\t"{t}\\x{f[0:2]}\\x{f[2:4]} {s}",',file=ofh)
    print('};', file=ofh)

